DATA:
  DIM: 2                  # data dimension
  BATCH_SIZE: 32 #32 for 256, 8 for 512
  TEST_BATCH_SIZE: 16 #128 #16
  DATA_PATH: '/data/weiweidu/criticalmaas_data/geophysics_data/lineaments_g256'
  TEST_MAP_PATH: '/data/weiweidu/criticalmaas_data/training_fault_line/AK_HinesCreek.png'
  TEST_DATA_PATH:  '/data/weiweidu/criticalmaas_data/geophysics_data/lineaments_g256/raw'
#   '/data/weiweidu/criticalmaas_data/geophysics_data/lineaments_g256'
#   '/data/weiweidu/criticalmaas_data/geophysics_data/Alaska_HGMmag_g256/'
  PRED_MAP_NAME: 'AK_HinesCreek_fault_line_pred'
  SHP_SAVE_PATH: 'AK_HinesCreek_fault_line_pred' 
  DATASET: 'US20-road-network-2D'     # Dataset name
  IMG_SIZE:  [256, 256]   #[256, 256]    # Input image size
  NUM_WORKERS: 1          # Number of data loading threads
  SEED: 10                # random seed for reproducibility

MODEL:
  NUM_CLASSES: 2          # Number of classes, overwritten in data preparation

  ENCODER:
    TYPE: deformable_transformer_backbone
    NAME: deformable_transformer_backbone
    HIDDEN_DIM: 512 #128 #256 #768
    POSITION_EMBEDDING: sine
    LR_BACKBONE: 5e-6
    NUM_FEATURE_LEVELS: 4
    BACKBONE: resnet101
    MASKS: False
    DILATION: False

    # parameters used else where
    IN_CHANS: 3
    DEPTHS: [4, 4, 8, 8, 18]

  DECODER:
    TYPE: deformable_transformer
    NAME: deformable_transformer
    HIDDEN_DIM: 512 #128 #256 #768
    NHEADS: 8
    ENC_LAYERS: 4 #4 #2
    DEC_LAYERS: 4 #4 #2
    DIM_FEEDFORWARD: 1024 #128 #512 #2048
    DROPOUT: 0.1  # 0.0
    ACTIVATION: relu  
    NUM_FEATURE_LEVELS: 4
    DEC_N_POINTS: 4
    ENC_N_POINTS: 4
    TWO_STAGE: False
    # NUM_QUERIES: 21
    AUX_LOSS: False
    WITH_BOX_REFINE: False
    # RLN_TOKEN: True

    OBJ_TOKEN: 70
    RLN_TOKEN: 1
    CONN_TOKEN: 1
    DUMMY_TOKEN: 1

    RLN_ATTN: True # only do comb RLN_ATTN True + RLN_TOKEN 0 and reverse

  MATCHER:
    C_CLASS: 3
    C_NODE: 5

TRAIN:
  EPOCHS: 200
  LR: 1e-4
  LR_BACKBONE: 1e-4
  WEIGHT_DECAY: 1e-4
  LR_DROP: 80
  CLIP_MAX_NORM: 0.1  # hardcoded

  SAVE_PATH: "./trained_weights/"          # save path for the checkpoint, log and val results
  VAL_INTERVAL: 400                  # validation interval
  SAVE_VAL: False                   # save validation data

  # loss weight
  LOSSES: ['class', 'nodes', 'edges', 'conns'] #
  W_BBOX: 2.0
  W_CLASS: 3.0 # {3.0, 5.0}
  W_CARD: 1.0
  W_NODE: 5.0 # {5.0, 8.0}
  W_EDGE: 4.0 # {4.0, 5.0}
  W_CONN: 1.0


log:
  exp_name: 'lineament_update_label_token70_distConn7_adjLoss20'
  message: "Baseline 2D relationformer for 2D sat network"
